# Generated by Django 5.1.3 on 2024-11-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=4, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
