# Generated by Django 5.1.3 on 2024-11-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='group_id',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'S'), ('medium', 'M'), ('large', 'L')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
