# Generated by Django 5.1.3 on 2024-11-10 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_sku_product_group_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color', 'size')},
        ),
    ]
