# Generated by Django 5.1.3 on 2024-11-10 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productvariant_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='group_id',
            new_name='group_sku_number',
        ),
    ]
