# Generated by Django 4.2.16 on 2024-11-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productvariant_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
