# Generated by Django 4.2.16 on 2024-11-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productvariantimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantimage',
            name='image1',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
