# Generated by Django 4.2.16 on 2024-11-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_brand_alter_category_name_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter category name (e.g., Hoodie, T-Shirt)', max_length=30, unique=True),
        ),
    ]
