# Generated by Django 4.2.16 on 2024-12-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_category_name_alter_productvariant_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], db_index=True, max_length=20, null=True),
        ),
    ]
